Importando Bibliotecas e Carregamento da base de dados

In [2]:
#importar as bibliotecas
import pandas as pd

#carregar os arquivos
df_analise = pd.read_csv("Vendas_Chocolate.csv", sep =";")

---

Inspeção Inicial (explorando e entendendo dados)

In [3]:
#inspeção inicial
display(df_analise.shape)
display(df_analise.head())
df_analise.info()

(3282, 7)

,Vendedor,País,Produto,Data,Valor,Caixas Enviadas,Data de Hoje
0,João Rocha,Reino Unido,Chocolate com Menta e Flocos,04/01/2022,"$5,320.00",180.0,03/02/2026
1,Vanderlei Teixeira,Índia,NaN,01/08/2022,"$7,896.00",94.0,NaN
2,Gisele Barbosa,Índia,Cubos de Manteiga de Amendoim,07/07/2022,"$4,501.00",91.0,NaN
3,Janaína Moreira,Austrália,Cubos de Manteiga de Amendoim,27/04/2022,"$12,726.00",342.0,NaN
4,João Rocha,Reino Unido,Cubos de Manteiga de Amendoim,24/02/2022,"$13,685.00",184.0,NaN

<class 'pandas.DataFrame'>
RangeIndex: 3282 entries, 0 to 3281
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Vendedor         3250 non-null   str
 1   País             3250 non-null   str
 2   Produto          3250 non-null   str
 3   Data             3282 non-null   str
 4   Valor            3282 non-null   str
 5   Caixas Enviadas  3250 non-null   float64
 6   Data de Hoje     1 non-null      str
dtypes: float64(1), str(6)
memory usage: 179.6 KB

---

Tratamento de Dados

In [4]:
#valores nulos
df_analise_tratada = df_analise.drop(columns= ["Data de Hoje"])
df_analise_tratada = df_analise_tratada.dropna()

#tipos de dados
df_analise_tratada["Valor"] = df_analise_tratada["Valor"].str.replace("$","").str.replace(",","").astype(float)
df_analise_tratada["Data"] = pd.to_datetime(df_analise_tratada["Data"], format = "%d/%m/%Y")

#valores duplicados
df_analise_tratada = df_analise_tratada.drop_duplicates()

#reset index
df_analise_tratada = df_analise_tratada.reset_index(drop = True)

display(df_analise_tratada)

,Vendedor,País,Produto,Data,Valor,Caixas Enviadas
0,João Rocha,Reino Unido,Chocolate com Menta e Flocos,2022-01-04,5320.00,180.0
1,Gisele Barbosa,Índia,Cubos de Manteiga de Amendoim,2022-07-07,4501.00,91.0
2,Janaína Moreira,Austrália,Cubos de Manteiga de Amendoim,2022-04-27,12726.00,342.0
3,João Rocha,Reino Unido,Cubos de Manteiga de Amendoim,2022-02-24,13685.00,184.0
4,Vanderlei Teixeira,Índia,Salgadinho Suave e Sedoso,2022-06-06,5376.00,38.0
...,...,...,...,...,...,...
3150,Karina Machado,Austrália,Especiais Apimentados Finos,2024-05-17,5303.58,354.0
3151,João Rocha,EUA,Chocolate Branco,2024-06-07,7339.32,121.0
3152,Célio Bonfim,Canadá,Xarope de Chocolate Orgânico,2024-07-26,616.09,238.0
3153,Doroti Santos,Índia,Bombas de Chocolate,2024-07-28,2504.62,397.0
3154,Karina Machado,Índia,Mordidas 70% Cacau,2024-05-23,5915.87,355.0

In [5]:
display(df_analise_tratada.describe())

                             Data         Valor  Caixas Enviadas
count                        3155   3155.000000      3155.000000
mean   2023-05-01 17:10:08.177496   6021.792041       164.105547
min           2022-01-03 00:00:00      7.000000         1.000000
25%           2022-06-30 00:00:00   2510.805000        71.000000
50%           2023-05-10 00:00:00   5220.800000       137.000000
75%           2024-03-01 12:00:00   8548.920000       232.000000
max           2024-08-31 00:00:00  26170.950000       778.000000
std                           NaN   4393.267909       123.288244

---

Feature Engineering

In [6]:
#feature engineering

#criar uma coluna para mes
df_analise_tratada["Mes"]= df_analise_tratada["Data"].dt.to_period("M")

#criar uma coluna para ano
df_analise_tratada["Ano"]= df_analise_tratada["Data"].dt.year
display(df_analise_tratada)

,Vendedor,País,Produto,Data,Valor,Caixas Enviadas,Mes,Ano
0,João Rocha,Reino Unido,Chocolate com Menta e Flocos,2022-01-04,5320.00,180.0,2022-01,2022
1,Gisele Barbosa,Índia,Cubos de Manteiga de Amendoim,2022-07-07,4501.00,91.0,2022-07,2022
2,Janaína Moreira,Austrália,Cubos de Manteiga de Amendoim,2022-04-27,12726.00,342.0,2022-04,2022
3,João Rocha,Reino Unido,Cubos de Manteiga de Amendoim,2022-02-24,13685.00,184.0,2022-02,2022
4,Vanderlei Teixeira,Índia,Salgadinho Suave e Sedoso,2022-06-06,5376.00,38.0,2022-06,2022
...,...,...,...,...,...,...,...,...
3150,Karina Machado,Austrália,Especiais Apimentados Finos,2024-05-17,5303.58,354.0,2024-05,2024
3151,João Rocha,EUA,Chocolate Branco,2024-06-07,7339.32,121.0,2024-06,2024
3152,Célio Bonfim,Canadá,Xarope de Chocolate Orgânico,2024-07-26,616.09,238.0,2024-07,2024
3153,Doroti Santos,Índia,Bombas de Chocolate,2024-07-28,2504.62,397.0,2024-07,2024
3154,Karina Machado,Índia,Mordidas 70% Cacau,2024-05-23,5915.87,355.0,2024-05,2024

___

Análise de crescimento de vendas

In [7]:
#análise temporal(dias/mes/ano)
import plotly.express as px

vendas_mes = df_analise_tratada[["Mes", "Valor"]]
vendas_mes = vendas_mes.groupby(by="Mes", as_index = False).sum()
display(vendas_mes)

grafico = px.bar(vendas_mes, x= vendas_mes["Mes"].astype(str), y ="Valor")
grafico.show()

        Mes      Valor
0   2022-01  860363.00
1   2022-02  699377.00
2   2022-03  726418.00
3   2022-04  653198.00
4   2022-05  740103.00
5   2022-06  836465.00
6   2022-07  772177.00
7   2022-08  709065.00
8   2023-01  900155.00
9   2023-02  729416.95
10  2023-03  784291.08
11  2023-04  700551.88
12  2023-05  771805.90
13  2023-06  904244.36
14  2023-07  832202.18
15  2023-08  774201.54
16  2024-01  991213.56
17  2024-02  745158.10
18  2024-03  782700.99
19  2024-04  715688.85
20  2024-05  793438.83
21  2024-06  895428.01
22  2024-07  878875.18
23  2024-08  802215.48

In [8]:
#análise de volume e ticket médio
vendas_ano = df_analise_tratada[["Ano", "Valor","Caixas Enviadas"]]
vendas_ano = vendas_ano.groupby(by="Ano", as_index = False).sum()

#Feature engineering(criando coluna de ticket médio e de percentual de crescimento)
vendas_ano["Ticket Médio"] = vendas_ano["Valor"] / vendas_ano["Caixas Enviadas"]
vendas_ano["% Crescimento Valor"] = vendas_ano["Valor"].pct_change()


display(vendas_ano.style.format({
    "Valor": "${:,.2f}",
    "Caixas Enviadas": "{:,.0f}",
    "Ticket Médio": "${:,.2f}",
    "% Crescimento Valor": "{:,.1%}"
}))

In [9]:
#análise por produto

df_produtos_anual = df_analise_tratada[["Ano", "Produto", "Valor"]]
df_produtos_anual= df_produtos_anual.groupby(["Ano", "Produto"], as_index = False).sum()
display(df_produtos_anual)
grafico = px.bar(df_produtos_anual, x = "Ano", y = "Valor", color = "Produto")
grafico.show()

     Ano                            Produto      Valor
0   2022                  99% Amargo e Puro  270144.00
1   2022    Amêndoas Cobertas com Chocolate  238847.00
2   2022                   Barras 85% Cacau  283297.00
3   2022      Barras Recheadas com Caramelo  231588.00
4   2022       Barras de Chocolate ao Leite  258867.00
..   ...                                ...        ...
61  2024  Gotas de Chocolate de Confeiteiro  281787.05
62  2024                 Mordidas 50% Cacau  355627.08
63  2024                 Mordidas 70% Cacau  237490.12
64  2024          Salgadinho Suave e Sedoso  370077.04
65  2024       Xarope de Chocolate Orgânico  327290.54

[66 rows x 3 columns]

---

Quais produtos mais vendem?

In [10]:
produtos_quantidade = df_analise_tratada.groupby("Produto")["Caixas Enviadas"].sum().sort_values(ascending=False).reset_index()
display(produtos_quantidade)
grafico = px.bar(produtos_quantidade, x = "Produto", y="Caixas Enviadas", title = "Quantidade de caixas vendidas por produto")
grafico.show()

                              Produto  Caixas Enviadas
0                  Mordidas 50% Cacau          28698.0
1           Salgadinho Suave e Sedoso          26602.0
2                   Chocolate Solúvel          25783.0
3       Barras Recheadas com Caramelo          25666.0
4                 Bombas de Chocolate          25543.0
5         Especiais Apimentados Finos          24728.0
6                    Chocolate Branco          24671.0
7        Barras de Chocolate ao Leite          24359.0
8                  Mordidas 70% Cacau          24225.0
9                     Depois das Nove          23994.0
10       Chocolate com Menta e Flocos          23971.0
11                  99% Amargo e Puro          23790.0
12      Cubos de Manteiga de Amendoim          23468.0
13        Chocolate com Mel de Manuka          22786.0
14       Xarope de Chocolate Orgânico          22726.0
15                   Barras 85% Cacau          22543.0
16               Chocolate de Laranja          22321.0
17       Barras de Frutas e Castanhas          21696.0
18  Gotas de Chocolate de Confeiteiro          21075.0
19             Chocolate de Framboesa          20782.0
20             Chocolate com Amêndoas          19700.0
21    Amêndoas Cobertas com Chocolate          18626.0

#### Insight:
O produto "Mordidas 50% Cacau" apresentou a maior quantidade de caixas vendidas, representando o item de maior demanda no período analisado.

---

Quais produtos geram mais faturamento?

In [11]:
faturamento = df_analise_tratada.groupby("Produto")["Valor"].sum().sort_values(ascending = False).reset_index()
display(faturamento)
grafico = px.bar(faturamento, x ="Produto" , y = "Valor", title= "Faturamento por produto")
grafico.show()

                              Produto       Valor
0           Salgadinho Suave e Sedoso  1092579.19
1                  Mordidas 50% Cacau  1046257.82
2                    Chocolate Branco  1029442.15
3       Cubos de Manteiga de Amendoim   971050.15
4                 Bombas de Chocolate   969549.16
5                    Barras 85% Cacau   925005.38
6                   99% Amargo e Puro   918604.16
7        Xarope de Chocolate Orgânico   904666.71
8         Especiais Apimentados Finos   890396.70
9        Chocolate com Menta e Flocos   865567.57
10       Barras de Chocolate ao Leite   842351.41
11             Chocolate com Amêndoas   841310.14
12        Chocolate com Mel de Manuka   833924.02
13                  Chocolate Solúvel   810206.20
14             Chocolate de Framboesa   803474.12
15                    Depois das Nove   793003.02
16  Gotas de Chocolate de Confeiteiro   791117.44
17               Chocolate de Laranja   784919.88
18       Barras de Frutas e Castanhas   749386.22
19    Amêndoas Cobertas com Chocolate   732994.93
20      Barras Recheadas com Caramelo   731624.06
21                 Mordidas 70% Cacau   671323.46

#### Insight:

Apesar de o produto "Salgadinho Suave e Sedoso" vender menos unidades comparado com o produto que mais vende (Mordidas 50% Cacau), ele gera maior faturamento, indicando um preço médio mais elevado

---

Existe relação entre a quantidade vendida e faturamento?

In [14]:
grafico = px.scatter(df_analise_tratada, x = "Caixas Enviadas", y = "Valor", color = "Produto", trendline="ols", title="Relação quantidade vendida e faturamento")
grafico.show()

#### Insight:

Apesar de o produto "Mordidas 50% Cacau "apresentar maior volume de caixas vendidas, o "Salgadinho Suave e Sedoso "foi o responsável pelo maior faturamento. Isso indica que o desempenho financeiro de um produto não depende apenas da quantidade vendida, mas também do seu valor por venda.

---

Existe algum pais que compra mais?

In [15]:
pais = df_analise_tratada.groupby("País")["Valor"].sum().sort_values(ascending = False).reset_index()
grafico = px.bar(pais, x = "País", y = "Valor", title="Países que mais realizam compras")
grafico.show()

faturamento_total = pais["Valor"].sum()
pais["Participação (%)"]= (pais["Valor"] / faturamento_total * 100).round(2)
display(pais)

            País       Valor  Participação (%)
0      Austrália  3503512.45             18.44
1    Reino Unido  3222420.18             16.96
2          Índia  3207754.38             16.88
3            EUA  3179030.34             16.73
4  Nova Zelândia  2959646.03             15.58
5         Canadá  2926390.51             15.40

#### Insights:
A Austrália apresentou o maior faturamento entre os países analisados, representando 18,44% do faturamento total da empresa. Esse resultado evidencia a importância desse mercado para o desempenho financeiro da organização e pode orientar decisões estratégicas relacionadas a investimentos e expansão comercial.

----

exportar df_analise_tratada para um novo CSV:

In [16]:
df_analise_tratada.to_csv(
    "dados_tratados.csv",
    index=False
)